name: ridwan
description: Flutter portfolio project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Navigation 2.0
  go_router: ^5.1.1

  # convenient code generator for get_it.
  injectable: ^1.5.3

  # Add .env
  envied: ^0.2.3

  # State management.
  flutter_bloc: ^8.1.1

  # responsive UI
  responsive_builder: ^0.4.3

  # ui kit for spin things
  flutter_spinkit: ^5.1.0

  # equality in dart
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  intl_generator: ^0.3.0
  retrofit_generator: ^4.0.3+1
  json_serializable: ^6.1.1

  # linter
  very_good_analysis: ^3.0.1
  injectable_generator: any
  freezed: ^2.1.0+1
  envied_generator: ^0.2.3
  # builder for go router
  go_router_builder: ^1.0.15

  # asset images or icon generator
  flutter_gen_core: ^5.1.0+1
  flutter_gen_runner: ^5.1.0+1

flutter_gen:
  output: lib/constants
  line_length: 140
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/

